# -*- coding: utf-8 -*-
"""Materializes the hand-labeled golden evaluation set from golden_candidates.csv.

Labels below were assigned by manually reading every one of the 214 sampled
threads (customer message + full historical conversation) against the
taxonomy in taxonomy.py. See report/decision_log.md for the escalation
policy rationale (escalation is NOT a fixed function of intent bucket).

Format per row: cand_id: (intent, escalate: bool, reason, note)
note is only populated for examples called out in the failure analysis.
"""
import pandas as pd

L = {
    1: ("feature_request_or_limitation", False, "content add request, no account data needed", ""),
    2: ("feature_request_or_limitation", False, "policy/limitation feedback", ""),
    3: ("login_account_access", True, "account changed without user action, needs identity verification", ""),
    4: ("account_billing", True, "payment/security concern, needs account verification", ""),
    5: ("content_availability", False, "region content gap, informational", ""),
    6: ("content_availability", False, "region availability, informational", ""),
    7: ("login_account_access", True, "account shows wrong plan state, needs lookup", ""),
    8: ("account_billing", True, "payment method update requires account access", ""),
    9: ("account_billing", True, "billing/charge investigation needs account data", ""),
    10: ("login_account_access", True, "account takeover / locked out, security", ""),
    11: ("account_billing", True, "plan change requires account access", ""),
    12: ("login_account_access", False, "language-support redirect is a deterministic auto-reply", "language mismatch: auto-handle via fixed redirect, not human escalation"),
    13: ("login_account_access", True, "locked out, no credentials, needs account recovery", ""),
    14: ("feature_request_or_limitation", False, "storage limit feedback", ""),
    15: ("playback_technical_issue", False, "device troubleshooting, self-serve first", "long thread; only escalates to DM after 2 failed self-serve attempts -- gold label reflects decision at FIRST contact"),
    16: ("playback_technical_issue", False, "sarcastic 'thanks' masks a playback complaint", "sarcasm: keyword 'thanks' would mis-bucket this as praise"),
    17: ("feature_request_or_limitation", False, "playlist content request", ""),
    18: ("redirect_other_team", False, "developer/API question, redirect", "brand's own historical agent misrouted this as a device issue first -- noisy label source"),
    19: ("login_account_access", True, "password reset broken, needs account-specific help", ""),
    20: ("login_account_access", True, "password reset ineffective, needs account lookup", ""),
    21: ("feature_request_or_limitation", False, "informational product question", ""),
    22: ("playback_technical_issue", False, "sarcastic 'thanks' masks a device bug report", "sarcasm"),
    23: ("account_billing", True, "student discount billing dispute, needs account check", ""),
    24: ("feature_request_or_limitation", False, "feature idea, redirect to community", ""),
    25: ("playback_technical_issue", False, "download troubleshooting", ""),
    26: ("account_billing", False, "non-English request -- auto-handle via language-channel redirect", "language mismatch"),
    27: ("account_billing", True, "unfulfilled gift card, needs account investigation", ""),
    28: ("praise_or_gratitude", False, "thanks, no action needed", ""),
    29: ("login_account_access", True, "long-standing login failure, needs account recovery", ""),
    30: ("login_account_access", True, "FB unlink login issue, needs account recovery", ""),
    31: ("account_billing", True, "family invite activation error, needs account check", ""),
    32: ("login_account_access", True, "can't authenticate via FB, needs account help", ""),
    33: ("playback_technical_issue", False, "playback troubleshooting, resolved via basic steps", ""),
    34: ("playback_technical_issue", False, "downloads disappearing, known issue doc covers it", ""),
    35: ("login_account_access", True, "email change locked account, needs recovery", ""),
    36: ("playback_technical_issue", False, "app not loading, likely transient outage/troubleshooting", ""),
    37: ("unclear_or_low_signal", False, "channel question with no stated problem; ask what's wrong", "low signal: correct move is a clarifying question, not escalation"),
    38: ("feature_request_or_limitation", False, "free-tier behavior explanation", ""),
    39: ("playback_technical_issue", False, "downloads deleted, known issue doc covers it", "historical brand reply oddly pivoted to asking for DM/account email -- noisy label"),
    40: ("account_billing", True, "premium downgraded unexpectedly, needs account check", ""),
    41: ("login_account_access", True, "no password reset email, needs account recovery", ""),
    42: ("playback_technical_issue", False, "Mac app performance troubleshooting", ""),
    43: ("login_account_access", True, "account inactive after password change, needs lookup", ""),
    44: ("playback_technical_issue", False, "ad-on-shuffle behavior, informational/bug report", ""),
    45: ("playback_technical_issue", False, "downloads disappearing, known issue doc covers it", ""),
    46: ("content_availability", False, "missing track from album, licensing", ""),
    47: ("feature_request_or_limitation", False, "offline limit explanation", ""),
    48: ("redirect_other_team", False, "internship inquiry, redirect", ""),
    49: ("account_billing", True, "student plan lapse/charge dispute, needs account check", ""),
    50: ("account_billing", True, "charged after cancellation, needs billing investigation", ""),
    51: ("content_availability", False, "song removed, licensing explanation", ""),
    52: ("unclear_or_low_signal", True, "unintelligible/spam text, needs human triage", "dataset noise: not a real support query at all"),
    53: ("praise_or_gratitude", False, "thanks, no action needed", ""),
    54: ("content_availability", False, "region availability, informational", ""),
    55: ("praise_or_gratitude", False, "positive feedback, no action needed", ""),
    56: ("feature_request_or_limitation", False, "web player feature gap (last.fm sync)", ""),
    57: ("content_availability", False, "region request, informational", ""),
    58: ("account_billing", False, "how to turn off auto-renew is policy info only, no account lookup", "billing bucket that should NOT escalate -- shows escalation isn't a pure function of intent"),
    59: ("playback_technical_issue", False, "glitching complaint, troubleshooting", ""),
    60: ("feature_request_or_limitation", False, "playlist content request + broken link", ""),
    61: ("playback_technical_issue", False, "sync troubleshooting, device info needed", ""),
    62: ("account_billing", True, "ad-eligibility/region billing dispute, needs account check", ""),
    63: ("account_billing", True, "unrecognized charge, needs billing investigation", ""),
    64: ("playback_technical_issue", False, "lock-screen controls troubleshooting", ""),
    65: ("playback_technical_issue", False, "downloads disappearing, known issue doc covers it", ""),
    66: ("account_billing", True, "gift subscription management, needs account access", ""),
    67: ("login_account_access", True, "premium login error, needs account check", ""),
    68: ("feature_request_or_limitation", False, "download limit workaround question", ""),
    69: ("content_availability", False, "region availability, informational", ""),
    70: ("redirect_other_team", False, "artist portal bug, redirect", ""),
    71: ("account_billing", True, "promo credit not received, needs account check", ""),
    72: ("content_error_report", False, "wrong artist attribution", ""),
    73: ("redirect_other_team", False, "artist rights/removal request, redirect", ""),
    74: ("feature_request_or_limitation", False, "personalization complaint (Discover Weekly)", "sarcastic 'thanks'"),
    75: ("content_availability", False, "region request, informational", ""),
    76: ("unclear_or_low_signal", False, "vague complaint with no detail; ask what's wrong", "low signal at intake -- the real issue only emerges after a follow-up question"),
    77: ("content_availability", False, "content removed, licensing explanation", "sarcastic 'thanks'"),
    78: ("feature_request_or_limitation", False, "playlist follower removal not supported", ""),
    79: ("login_account_access", True, "password reset broken, needs account help", ""),
    80: ("login_account_access", True, "repeated logout, needs account investigation", ""),
    81: ("content_availability", False, "incomplete album, licensing", ""),
    82: ("feature_request_or_limitation", False, "content request (soundtrack)", ""),
    83: ("login_account_access", True, "stale email on account, needs update via account access", ""),
    84: ("feature_request_or_limitation", False, "explicit filter feature request", ""),
    85: ("login_account_access", True, "password reset failure; tweet also exposes account PII", "PII exposed in public tweet -- needs secure (DM) handling, flagged before responding"),
    86: ("content_error_report", False, "wrong artist attribution", ""),
    87: ("playback_technical_issue", False, "web player crash troubleshooting", ""),
    88: ("account_billing", True, "trial/discount conflict billing issue, needs account check", ""),
    89: ("account_billing", True, "promo credit delayed, needs account check", ""),
    90: ("account_billing", True, "verified artist account issue, needs account access", ""),
    91: ("feature_request_or_limitation", False, "recommendation algorithm feedback", ""),
    92: ("playback_technical_issue", False, "ad-free timer bug report, forwarded to devs", ""),
    93: ("playback_technical_issue", False, "downloads disappearing weekly, known issue doc", ""),
    94: ("login_account_access", True, "locked out; tweet also exposes account PII", "PII exposed in public tweet"),
    95: ("feature_request_or_limitation", False, "device support roadmap question", ""),
    96: ("feature_request_or_limitation", False, "feature request (Last.fm remote)", ""),
    97: ("account_billing", True, "charged despite ineligible student status, needs account check", ""),
    98: ("feature_request_or_limitation", False, "offline limit removal plea", ""),
    99: ("content_availability", False, "content removed repeatedly, licensing", ""),
    100: ("content_error_report", False, "wrong artist attribution", ""),
    101: ("content_error_report", False, "audio encode/tempo defect report", ""),
    102: ("feature_request_or_limitation", False, "lyrics feature request", ""),
    103: ("account_billing", True, "duplicate charge, needs billing investigation", ""),
    104: ("login_account_access", True, "FB unlink login issue, needs account recovery", ""),
    105: ("feature_request_or_limitation", False, "device optimization request", ""),
    106: ("feature_request_or_limitation", False, "metadata/credits feature request", ""),
    107: ("feature_request_or_limitation", False, "offline limit complaint", ""),
    108: ("unclear_or_low_signal", False, "vague dig at support with no stated problem; ask what's wrong", "low signal"),
    109: ("feature_request_or_limitation", False, "year-end stats question", ""),
    110: ("feature_request_or_limitation", False, "hide-content feature request", ""),
    111: ("playback_technical_issue", False, "downloaded albums disappearing, known issue", ""),
    112: ("feature_request_or_limitation", False, "download limit complaint", ""),
    113: ("login_account_access", True, "email not recognized, needs account check", ""),
    114: ("login_account_access", True, "email wrongfully changed, locked out, needs secure recovery", ""),
    115: ("content_availability", False, "region-limited preview, informational", ""),
    116: ("account_billing", True, "plan change (family), needs account access", ""),
    117: ("content_availability", False, "region availability, informational", ""),
    118: ("content_error_report", False, "wrong track mapping bug", ""),
    119: ("feature_request_or_limitation", False, "song limit hit, informational", ""),
    120: ("feature_request_or_limitation", False, "lyrics feature question, informational", ""),
    121: ("playback_technical_issue", False, "shuffle bug on cellular, troubleshooting", ""),
    122: ("playback_technical_issue", False, "shuffle algorithm complaint", ""),
    123: ("feature_request_or_limitation", False, "saving limit question", ""),
    124: ("playback_technical_issue", False, "shuffle algorithm complaint", ""),
    125: ("login_account_access", False, "login/blank-screen bug; troubleshoot device first", "login issue that does NOT need escalation at first contact"),
    126: ("playback_technical_issue", False, "search error, likely resolved outage", ""),
    127: ("content_availability", False, "release delay by region, informational", ""),
    128: ("feature_request_or_limitation", False, "ad content feedback", ""),
    129: ("feature_request_or_limitation", False, "offline limit anxiety, informational", ""),
    130: ("redirect_other_team", False, "artist search-result removal, redirect", ""),
    131: ("feature_request_or_limitation", False, "content request", ""),
    132: ("content_error_report", False, "wrong artist link", ""),
    133: ("account_billing", True, "Hulu bundle access issue, needs account check", ""),
    134: ("playback_technical_issue", False, "offline sync bug, troubleshooting", ""),
    135: ("feature_request_or_limitation", False, "device optimization request", ""),
    136: ("feature_request_or_limitation", False, "recommendation quality feedback", ""),
    137: ("feature_request_or_limitation", False, "song limit complaint", ""),
    138: ("login_account_access", True, "FB login loop, needs account recovery", ""),
    139: ("redirect_other_team", False, "job inquiry, redirect", ""),
    140: ("account_billing", True, "charged 3x, needs billing investigation", ""),
    141: ("account_billing", True, "student discount + Hulu access issue, needs account check", ""),
    142: ("content_error_report", False, "wrong artist link", ""),
    143: ("account_billing", True, "family plan member removal, needs account access", "sarcastic 'thank you'"),
    144: ("playback_technical_issue", False, "lock-screen artwork bug, troubleshooting", ""),
    145: ("account_billing", True, "premium not activating after purchase, needs account check", ""),
    146: ("feature_request_or_limitation", False, "feature suggestions (label search, multi-station)", ""),
    147: ("playback_technical_issue", False, "cellular download setting bug", ""),
    148: ("playback_technical_issue", False, "playlist playback bug, troubleshooting", ""),
    149: ("feature_request_or_limitation", False, "content request (specific track)", ""),
    150: ("content_availability", False, "tracks removed, licensing", ""),
    151: ("account_billing", True, "billing sentiment complaint routed to DM, needs account check", "sarcastic 'spotify cares'"),
    152: ("content_availability", False, "song unavailable, informational", ""),
    153: ("account_billing", True, "family premium issue, already in DM, needs account access", ""),
    154: ("feature_request_or_limitation", False, "playlist UX feature request", ""),
    155: ("feature_request_or_limitation", False, "listening history feature request", ""),
    156: ("playback_technical_issue", False, "download limit error despite deleting, troubleshooting", ""),
    157: ("content_availability", False, "region launch question, informational", ""),
    158: ("login_account_access", True, "password reset broken, needs account help", ""),
    159: ("feature_request_or_limitation", False, "content request", ""),
    160: ("unclear_or_low_signal", False, "vague issue, ask for specifics", "low signal"),
    161: ("feature_request_or_limitation", False, "how-to question, self-resolved", ""),
    162: ("praise_or_gratitude", False, "lighthearted comment, no real ask", ""),
    163: ("feature_request_or_limitation", False, "content request", ""),
    164: ("content_availability", False, "region availability check", ""),
    165: ("playback_technical_issue", True, "playlists vanished, needs account-level investigation", ""),
    166: ("account_billing", True, "presale code missing, needs account check", ""),
    167: ("feature_request_or_limitation", False, "offline limit + sorting question", ""),
    168: ("feature_request_or_limitation", False, "device update request", ""),
    169: ("login_account_access", True, "can't log in from desktop, needs account help", ""),
    170: ("redirect_other_team", False, "platform legitimacy question, informational", ""),
    171: ("playback_technical_issue", True, "downloaded content vanished, needs account-level investigation", ""),
    172: ("feature_request_or_limitation", False, "personalization complaint", ""),
    173: ("account_billing", True, "Hulu bundle verification, needs account check", ""),
    174: ("login_account_access", True, "complex login failure, needs account recovery", ""),
    175: ("feature_request_or_limitation", False, "content request", ""),
    176: ("login_account_access", True, "Alexa/FB linking login issue, needs account recovery", ""),
    177: ("feature_request_or_limitation", False, "download pre-selection feature request", ""),
    178: ("account_billing", True, "premium disappeared, needs account check", ""),
    179: ("content_availability", False, "song unavailable, informational", ""),
    180: ("content_availability", False, "album removed, licensing", ""),
    181: ("content_availability", False, "region availability, informational", ""),
    182: ("login_account_access", True, "app crash + login failure, needs account help", ""),
    183: ("redirect_other_team", False, "job inquiry, redirect", ""),
    184: ("feature_request_or_limitation", False, "service-speed complaint, general feedback", ""),
    185: ("account_billing", True, "triple charge, needs billing investigation", ""),
    186: ("content_availability", False, "region download restriction, informational", ""),
    187: ("feature_request_or_limitation", False, "playlist playback control feature request", ""),
    188: ("content_availability", False, "content removed by region, licensing", "angry tone"),
    189: ("feature_request_or_limitation", False, "family/partner listening feature question", ""),
    190: ("account_billing", True, "unexpected cancellation, needs account check", ""),
    191: ("feature_request_or_limitation", False, "content request", ""),
    192: ("feature_request_or_limitation", False, "playlist curation complaint", ""),
    193: ("account_billing", True, "promo signup form error, needs account check", ""),
    194: ("redirect_other_team", False, "developer API outage question, redirect", ""),
    195: ("account_billing", True, "invite code rejected, needs account check", ""),
    196: ("playback_technical_issue", False, "can't save downloaded songs, troubleshooting", ""),
    197: ("feature_request_or_limitation", False, "label browsing feature request", ""),
    198: ("feature_request_or_limitation", False, "PS4 app feature requests", ""),
    199: ("redirect_other_team", False, "job inquiry, redirect", ""),
    200: ("playback_technical_issue", False, "playlist playback stopping bug, troubleshooting", ""),
    201: ("unclear_or_low_signal", False, "vague message, ask for specifics", "low signal"),
    202: ("playback_technical_issue", False, "playback error, troubleshooting", ""),
    203: ("login_account_access", True, "new user sign-in failure, needs account check", ""),
    204: ("feature_request_or_limitation", False, "UI feature request (artwork size)", ""),
    205: ("account_billing", True, "grace period request, needs account check", ""),
    206: ("feature_request_or_limitation", False, "plan info question, informational", ""),
    207: ("feature_request_or_limitation", False, "limit complaint (venting), informational", ""),
    208: ("login_account_access", True, "family plan recognition issue, needs account check", ""),
    209: ("login_account_access", True, "FB-only login limitation, needs account help", ""),
    210: ("playback_technical_issue", True, "Discover Weekly not refreshing, needs account-level investigation", ""),
    211: ("feature_request_or_limitation", False, "storage limit + organization feature request", ""),
    212: ("account_billing", True, "region move breaks account, needs account check", ""),
    213: ("feature_request_or_limitation", False, "content request", ""),
    214: ("redirect_other_team", False, "catalog browsing by label feature, redirect/feedback", ""),
}

cands = pd.read_csv("data/processed/golden_candidates.csv")
assert set(L.keys()) == set(cands["cand_id"]), f"label/candidate mismatch: {set(cands['cand_id']) ^ set(L.keys())}"

rows = []
for _, r in cands.iterrows():
    intent, escalate, reason, note = L[r["cand_id"]]
    rows.append({
        "id": r["cand_id"],
        "thread_id": r["thread_id"],
        "context_before": r["context_before"],
        "customer_message": r["customer_message"],
        "intent_gold": intent,
        "escalate_gold": escalate,
        "escalate_reason_gold": reason,
        "note": note,
        "historical_brand_reply": r["brand_reply"],
        "historical_full_conversation": r["full_conversation"],
        "keyword_bucket": r["bucket"],
    })

out = pd.DataFrame(rows)
out.to_csv("data/eval/golden_set.csv", index=False, encoding="utf-8")
print(f"Wrote {len(out)} labeled examples to data/eval/golden_set.csv")
print("\nIntent distribution:")
print(out["intent_gold"].value_counts())
print("\nEscalate distribution:")
print(out["escalate_gold"].value_counts())
